steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies (npm install)'

- script: npm run test:lint
  displayName: 'Run lint check'

- script: npm run test:validate
  displayName: 'Run TypeScript Declaration / Flow checks'

- bash: |
    npm install -g tap-junit
    npm run test:ava | tap-junit > test-results.xml
  env:
    CI: true
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: './test-results.xml'
    testRunTitle: '$(System.JobIdentifier) tests'
  displayName: 'Publish test results'

- script: npm run report-coverage
  env:
    COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN_SECRET)
  continueOnError: true
  displayName: 'Publish coverage results'
